### ISSUE TITLE
request data button doesn't go away on expire

### ISSUE THREAD

**Issue by keiracodes** [tekoh/nypsi#528]
on expire, the "request data" button also doesn't expire but obviously it can't be used (this interaction failed)

image of what i mean below

the "expired" screen also looks different from other ones: see screenshot below

thank u

**Comment by keiracodes** [comment]
<img width="391" alt="Screenshot 2022-08-01 at 3 44 01 AM" src="https://user-images.githubusercontent.com/109384098/182088189-aff11c09-e0b0-474d-91e3-f64a5693de3b.png">
since it didn't want to load here's the first ss

**Comment by keiracodes** [comment]
<img width="612" alt="Screenshot 2022-08-01 at 3 44 51 AM" src="https://user-images.githubusercontent.com/109384098/182088322-f1388c37-25f2-4ed6-a4a1-1ad18ac35844.png">

<img width="359" alt="Screenshot 2022-08-01 at 3 45 18 AM" src="https://user-images.githubusercontent.com/109384098/182088386-ade5e985-2271-440d-bbc6-7e2225d6470f.png">

here's the images since github doesn't like them being in the description

**Comment by tekoh** [comment]
both r easily fixed with these lines

https://github.com/tekoh/nypsi/blob/ea05c259d66fc67991a2a3059fcf98d55d020a56/src/commands/profile.ts#L74-L75

@superboxes would you like to make your first pr

**Comment by keiracodes** [comment]
_suspenseful music plays_
