### ISSUE TITLE
$itop of cookie/cake doesnt list me

### ISSUE THREAD

**Issue by superboxes** [tekoh/nypsi#555]
Not sure how this happens, its just im sometimes on the leaderboard and sometimes not. 

Here are some pictures:

leaderboard: https://i.imgur.com/Iko6XKg.png
cookie count: https://i.imgur.com/LqjvkTp.png

**Comment by tekoh** [comment]
only lists people above a certain balance for optimisation (if it fetches everyone then it has to loop through many thousands more people)

**Comment by superboxes** [comment]
> only lists people above a certain balance for optimisation (if it fetches everyone then it has to loop through many thousands more people)

noted, my bad!
