### ISSUE TITLE
fix: odds for bankrob aren't performing properly (not an issue)

### ISSUE THREAD

**Issue by keiracodes** [tekoh/nypsi#637]
as the title says, the new bankrob system doesn't calculate odds based on something like how much money is stored in the bank you're attempting to rob, and because of this, odds are unfair and just not working properly

this could be fixable by instead calculating odds based on the amount of money is in the bank, a user's prestige/balance, etc..

**Comment by tekoh** [comment]
it's not supposed to, its a consistent 35% chance

**Comment by keiracodes** [comment]
just seen this now, and alright
