### ISSUE TITLE
$cars is broken

### ISSUE THREAD

**Issue by meikacodes** [tekoh/nypsi#979]
the command doesn't output anything and just places a cooldown on the user
pls fix >:)

**Comment by meikacodes** [comment]
<img width="476" alt="Screenshot 2023-04-08 at 04 26 32" src="https://user-images.githubusercontent.com/109384098/230697384-acc1cd48-9b98-4933-ad60-ca497cb970da.png">
here's a screenshot of the issue

**Comment by OrionLmao** [comment]
nah its just a skill issue
